# Generated by Django 5.2 on 2025-10-15 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message_logging", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MessageLog",
        ),
    ]
